### PR TITLE
Add Horizon: Zero Dawn

### PR DESCRIPTION
**Pull request by tht1kd**

### CODE REVIEW

**Comment by kbuzsaki** [comment]
Deployed :)

**Comment by AltinCloak** [comment]
hey @tht1kd , since I've also been working on some bingo boards for HZD. would it be ok with you for me to ask for your board variant to be renamed 'TJ-fullgame' to fit with the way that I'm naming my boards?

**Comment by tht1kd** [comment]
> hey @tht1kd , since I've also been working on some bingo boards for HZD. would it be ok with you for me to ask for your board variant to be renamed 'TJ-fullgame' to fit with the way that I'm naming my boards?

@AltinCloak Sorry for the delayed response. Is there anything different we could go by, such as short game, or some variant (such as machine hunting only or something). I know most games here have variants based on what they are, versus just a name no one will associate with.

**Comment by AltinCloak** [comment]
the way I'm building the collection of building is that the board is based on what section of the world it's played in (Sacred land, The Frozen Wilds, Main Game, etc.) since your board has goals from the entire game I would have called it fullgame, and then we would have two different fullgame variants. 
I agree that just putting a name behind a name doesn't mean much, but I'm just trying to think of a good way to differentiate the two different boards.

**Comment by tht1kd** [comment]
fair, can we combine the two full games? We had trouble with a couple of our difficulty levels of finding goals. wonder if we can just combine them, unless you arent particular to a lot of our goals we made.

**Comment by AltinCloak** [comment]
we could combined them, my full game isn't done cause I'm planning on finishing the maingame bingo board first. and I didn't have problems with many of your goals, the no fast travel and take blaze canisters of grazers and the quantity and placement of difficulty but yeah

**Comment by tht1kd** [comment]
yea, let me know if you want to collab on difficulty changes or anything. Thanks for reaching out :) Cool too see someone else adding more variants :)

**Comment by AltinCloak** [comment]
well, I'm a speedrunner for the game and I've been wanting some new ways to play it

**Comment by AltinCloak** [comment]
here is the github for the boards I'm working on. I'm working on maingame right now and then I'll combine maingame and The Frozen Wilds into a fullgame bingo

**Pull request merged**
