### PR TITLE
rebalanced goals in pokemon_emerald_old_randomizer_short_generator

### PR DESCRIPTION
**Pull request by mewtwo15026**
In pokemon_emerald_old_randomizer_short_generator.js:
- Removed several redundant and/or easy goals
- Added some new goals

### CODE REVIEW

**Comment by kbuzsaki** [comment]
This PR has a lot of conflicts / unrelated diffs. Is the change that you want just the 13221b62aaf938ee6b10da5deac8e1db4de099a1 commit?

**Comment by mewtwo15026** [comment]
Yeah, I only want the changes to pokemon_emerald_randomizer_short.js - the 13221b6 commit should be fine.

**Comment by mewtwo15026** [comment]
I know I changed the goals list in pokemon_emerald_old_randomizer_**_short_**_generator.js - the old generator for longer runs is the one that hasn't been changed, but that one isn't mine.

**Comment by kbuzsaki** [comment]
I thought I had checked old\_randomizer\_short already, but I finally got around to diffing the branches and found the change. Implemented in 19dfbf4ccf4432c68f5146528643f14ea90f302a and up on the site now.

**Pull request closed without merging**
