### PR TITLE
New beta quest goals

### PR DESCRIPTION
**Pull request by SlyryD**
Draft of new beta quest goals for discussion

### CODE REVIEW

**Comment by kbuzsaki** [comment]
This looks fine, are you looking for discussion from anyone in particular?

**Comment by SlyryD** [comment]
Yeah I need to ping the community again. I think my message was buried a bit. Thanks for following up though :D

**Comment by SlyryD** [comment]
Okay, this should be good to go! Thanks for your help!

**Comment by kbuzsaki** [comment]
This is deployed now :)

**Pull request merged**
