### PR TITLE
Pull out synerGen into generator_bases and Update the Pikmin 3 generator

### PR DESCRIPTION
**Pull request by AbsolutelyAsh**
-ported it to synerGen
-added roughly 70 goals
-removed roughly 25 shitty goals
-fixed wording, typos, and grammar in many goals
~~don't tell APerson13 about this~~

### CODE REVIEW

**Comment by kbuzsaki** [comment]
Hi there, is "synerGen" the common name for this type of generator? I think I've seen it used for Hollow Knight and maybe a couple other games.

If this is a common generator type that people are using I'll extract it out into the generator_bases directory to dedupe code and then maybe advertise it as supported / make it work as a "custom" generator.

**Comment by AbsolutelyAsh** [comment]
synerGen is the name of this generator, yes. Currently it's being used for Hollow Knight, Pikmin 2, and now Pikmin 3. They all use slight variations currently, so I'll work on making a version compatible with all of them.

**Comment by AbsolutelyAsh** [comment]
Alright, I've updated every generator that uses synerGen to be consistent-- You should be able to pull it out for all of those.

**Comment by AbsolutelyAsh** [comment]
I've pulled out synerGen into generator_bases for every generator that uses it now, hopefully I did it all right

**Comment by kbuzsaki** [comment]
This is up now, thanks for pulling the duped generators out :) 

You even fixed a small bug in the Portuguese variant, it had a threshold tweaked to a slightly different value from the English variant that caused 1 of the 5 test cards to be generated differently :)

**Pull request merged**
