### PR TITLE
Rebase and unify new card form and new room form, semi-dynamic chat

### PR DESCRIPTION
**Pull request by FelixNemis**
-Rebase the new-card form branch and update all the stuff that went with the new variant system
-Using django-crispy-forms to make a less hacky room form that also renders the new card form (the submitting of the new card form is still separate though)
-Only load the last 24 hours of chat events, display a clickable message at the top to load the whole chat history, not sure if this is what you want but I figured I'd try it out, seems like it would work well to me
-Get the new card functionality working with the variant selector (easy now that they share rendering code and some javascript)

### CODE REVIEW

**Comment by kbuzsaki** [comment]
This is really solid! When testing it out, I only found one small issue: If the current card has "hide card initially", the "hide card initially" checkbox is pre-checked if you receive a new card event, but not on a clean page load.

I still need to take another look over the code to see if I spot anything there, and then figure out the right strategy for rolling out.

Some miscellaneous other thoughts, none of them blocking:
- [ ] Spectators can currently create new cards. Is that the right thing to do? They can currently send chat messages but cannot click goals.
- [ ] The new card can change the lockout mode, but it doesn't get announced in the new card event message. Should it be announced or is that too much clutter?
- [ ] Is it worth trying to make the old board available in the room somehow? I think this is probably too much complexity to be worth doing, but people might ask for it.
- [ ] Ditto, but for old game types/seeds on the room history page. This is less complex so it might be worth doing in the future.

**Comment by FelixNemis** [comment]
Yeah, I don't think spectators should be able to generate new cards.
I can fix that hide card checkbox issue when I get home

**Comment by kbuzsaki** [comment]
On giving it some more thought, I think spectators should be able to make a new card. You can create a room as a spectator, so sometimes e.g. tournament admins will do that. It makes sense for them to be able to make a new card in that case.

**Comment by kbuzsaki** [comment]
Finished reviewing and merged. Thanks again for doing such a thorough job :)

Rolling this out will require at least a bit of downtime so that I can apply the migrations and update the static files. If something goes wrong, it could take longer to fix or rollback. Since it's a non-trivial change, I'd prefer not to do it close to the Friday/Saturday/Sunday peak and would like to give users some notice re: the interruption.

I'll put together a small banner notice on Sunday evening and then deploy the change sometime Monday.

**Pull request merged**
