### PR TITLE
Increase contrast between colors

### PR DESCRIPTION
**Pull request by FelixNemis**
Modified colors to increase contrast between them, this is especially helpful for blue and green.

Old:
old_contrast

New:
new_contrast

### CODE REVIEW

**Comment by kbuzsaki** [comment]
Hm, I'm onboard with the idea behind this pull request but the colors seem a bit dark to me. 

What do you think of this?
lightened board

**Comment by FelixNemis** [comment]
Here's another version with lighter colors:

new_contrast2

**Comment by FelixNemis** [comment]
Actually I think the orange is a bit too saturated, I'll make another one real quick

**Comment by FelixNemis** [comment]
there:

new_contrast3

**Comment by kdhuynh** [comment]
If you guys are interested in another suggestion:

New:
image

Compared to Old:
image

**Comment by kbuzsaki** [comment]
I like the brighter colors in @kdhuynh's suggestion, what do you think about the blue/green contrast there, @FelixNemis?

**Comment by FelixNemis** [comment]
I like those, though I do think the green needs to be slightly more saturated like in mine. It does look good but blue and green still don't have much contrast between each other, so I think either the blue needs to be more of a pure blue or the green needs more saturation.

**Comment by FelixNemis** [comment]
Here's an example with a lighter green and a more pure blue, the lack of green in the blue kinda makes it look darker but it does help with the contrast from green:

contrast_more_blue

**Comment by FelixNemis** [comment]
here's a comparison of the color palletes, notice how @kdhuynh's green and blue are much closer to each other.

color_pallettes

**Comment by kdhuynh** [comment]
That's a cool way to view the color palletes, you can definitely see the difference in contrast

I just liked the look of cyan in the original pallete and didn't want to abandon it completely, so I tried to saturate the colors more to help with the contrast. 

Here's another version that compromises the cyan a bit more and makes the green pop a bit extra.

image

**Comment by FelixNemis** [comment]
I like this one a lot

**Comment by kbuzsaki** [comment]
I'm happy with those colors as well. Would you mind submitting a pull request with the change, @kdhuynh?

**Comment by FelixNemis** [comment]
It's a little better, I still would rather have the blue and green have a bit more contrast. It's definitely a good improvement over the current colors though
pallette2

**Comment by kbuzsaki** [comment]
Closing this pull request since we're going with the changes from #12.

**Pull request closed without merging**
