### PR TITLE
Random seed

### LINKED ISSUE #6: Add a way to ensure that multiple rooms have the same seed
When multiple teams are racing against each other in bingo blackout, they need to make sure that they're all racing using the same board. 

This is done by human coordination and can be error prone, so it would be nice to have a built in way to make sure multiple rooms have the same seed.

### LINKED ISSUE #7: Let the site choose a random seed if a player doesn't want to provide one

### PR DESCRIPTION
**Pull request by FelixNemis**
fixes #7

### CODE REVIEW

**Comment by FelixNemis** [comment]
wait some of these commits are from the other pull request
not sure what went wrong

**Comment by kbuzsaki** [comment]
The changes in d18e1cc look good to me. 

You're right though that it looks like this change was branched from [FelixNemis:increaseContrast](https://github.com/FelixNemis/bingosync/commits/increaseContrast), so those should be removed before merging.

**Comment by FelixNemis** [comment]
That should fix it

**Comment by kbuzsaki** [comment]
Alright, merged in. Thanks!

**Pull request merged**
