### PR TITLE
Fix text size of goals on card reveal, hide seed while card is hidden

### PR DESCRIPTION
**Pull request by FelixNemis**
When the board is hidden, the seed is still visible and people could use this to peak at the card early.
This hides the seed from the visible and hidden markup and javascript log, it's not impossible to get the seed but at least it's not trivial now :P 
Also fixes the automatic text fitting in goals when the board is revealed.
Also hides console logging of all incoming events.

### CODE REVIEW

**Comment by kbuzsaki** [comment]
Hm, the seed hiding/revealing on new card events doesn't work quite right when you refresh the page or when there are multiple new card events (I think only the most recent seed should be hidden, older ones it's fine to reveal).

Some other thoughts:
- I think it's fine to leave the seed hidden in the HTML, we don't have to add it in dynamically when revealing the board. That should make the code simpler. For comparison, that's how the hidden board itself works-- the goal text is there all along, it's just covered and hidden with css.
- The seed is also visible on the room history page. It's fine to leave that I think, unless you notice people mention it again. If someone does bring it up, I suppose it could be hidden until the first reveal event for that game.
- The ROOM_SETTINGS still gets logged in bingosync.html, which shows the seed in the console. I'm not sure if people will check that either though?

I tried fixing the hiding/revealing issue this morning, but haven't gotten it to a state that I like yet. Here's what I used in NewCardEvent to detect if it was the most recent event, if you want to mess around yourself:

```
    @property
    def is_current(self):
        new_card_events = NewCardEvent.objects.filter(player__room=self.player.room).order_by("timestamp")
        return new_card_events.last() == self
```

**Comment by FelixNemis** [comment]
It was working for me with multiple events and page reloading, I can do more testing later today

**Comment by FelixNemis** [comment]
As for leaving it out of the markup, the reason I thought to do that is because of the "inspect element" feature that a lot of people already know about, you could simply right click on "Hidden" -> inspect, and the seed is right there. I know the board text is still on the page already but it's nested several layers into a table that have to be expanded so it seems slightly more hidden.
Just my thought process I guess

**Comment by FelixNemis** [comment]
I fixed the seed in chat not working on page reload, and hid the seed in the room history
Also removed the console log of ROOM_SETTINGS since it doesn't need to be there anyway

**Comment by kbuzsaki** [comment]
Deployed to production now

**Pull request merged**
