### PR TITLE
Update zelda_botw_english.js

### PR DESCRIPTION
**Pull request by armuell**
The zelda botw speedrunning discord has revised the goal list by adding new goals and changing the difficulty of some old ones. French/Japanese translations are currently being done but if at all possible I was hoping this pr could be merged in and published so the new goal list could be used during Bingothon (a livestreaming charity event that starts in 6 days on May 28th at 7am EST)

### CODE REVIEW

**Comment by armuell** [comment]
@kbuzsaki I have no doubt you are a busy person but just wanted to check in to see what the odds are of this getting merged in today?

**Comment by 31PNMR** [comment]
I'm looking forward to this being merged. We have some bingo races coming up.

**Comment by armuell** [comment]
https://i.imgflip.com/5d7wc2.jpg

**Comment by armuell** [comment]
All memes aside I'm not gonna pretend like I now the workflow you have to go through to publish production change to bingosync. But I want to run a botw bingo tourney soon and I know a lot of people want to try these new goals out. And features like #140 and #141 would be super useful for everyone

**Comment by kbuzsaki** [comment]
Memes don't help anything, though sometimes a reminder can :)

I did an upload of generators last week but apparently I missed this one. The update is live now.

**Pull request merged**
